
services:
  sharelatex:
    container_name: sharelatex
    image: 'sharelatex/sharelatex:${SHARELATEX_IMAGE_VERSION:-3.5}'
    depends_on:
      - 'sharelatex-mongo'
      - 'sharelatex-redis'
    environment:
      REDIS_HOST: 'sharelatex-redis'
      SHARELATEX_ADMIN_EMAIL: '${ROOT_EMAIL:-changeme@changeme.org}'
      SHARELATEX_APP_NAME: 'ShareLaTeX'
      # SHARELATEX_HEADER_IMAGE_URL: 'http://somewhere.com/mylogo.png'
      SHARELATEX_MONGO_URL: 'mongodb://sharelatex-mongo/sharelatex'
      SHARELATEX_NAV_TITLE: '${HOST_DOMAIN} - ShareLaTeX'
      SHARELATEX_REDIS_HOST: 'sharelatex-redis'
      SHARELATEX_SITE_URL: 'https://latex.${HOST_DOMAIN}'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sharelatex.entrypoints=websecure"
      - "traefik.http.routers.sharelatex.tls=true"
      - "traefik.http.routers.sharelatex.rule=Host(`latex.${HOST_DOMAIN}`)"
      - "traefik.http.services.sharelatex.loadbalancer.server.port=80"
      - 'traefik.docker.network=traefik-public'
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - 'traefik-public'
      - 'latex_net'
    restart: 'always'
    volumes:
      - '${DOCKERDIR}/sharelatexdata:/var/lib/sharelatex'
      - '${DOCKERDIR}/sharelatexpackages:/usr/local/texlive:rw'

  sharelatex-mongo:
    container_name: sharelatex-mongo
    image: 'mongo:4.0'
    healthcheck:
      test: ['CMD', 'echo', 'db.runCommand("ping").ok',
             '|', 'mongo', 'localhost:27017/test', '--quiet']
    labels:
      traefik.enable: false
    #user: "1000:1000"
    networks:
      - 'latex_net'
    restart: 'always'
    volumes:
      - '${DOCKERDIR}/sharelatexdb:/data/db'

  sharelatex-redis:
    container_name: sharelatex-redis
    image: 'redis:6.0-alpine'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    labels:
      traefik.enable: false
    #user: "1000:1000"
    networks:
      - 'latex_net'
    restart: 'always'
    volumes:
      - '${DOCKERDIR}/sharelatexredis:/data'

networks:
  latex_net: { }