

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${TZ}"
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - ${DOCKERDIR}/qbittorrent/appdata:/config
      - ${DOCKERDIR}/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.rule=Host(`torrent.${HOST_DOMAIN}`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    restart: unless-stopped
    networks:
      - traefik_net