apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-general-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.5
    path: /mnt/main/docker
