
services:
  traefik:
    image: traefik:${TRAEFIK_DOCKER_TAG:-2.10.7}
    container_name: ${TRAEFIK_CONTAINER_NAME:-traefik}
    restart: unless-stopped
    networks:
      - traefik-public
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yaml:/etc/traefik/dynamic/traefik.yaml:ro  # mount dynamic configuration file
      - /home/jon/.certs/:/etc/certs/:ro
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --log.level=${TRAEFIK_LOG_LEVEL:-ERROR}  # set to INFO for production
      - --api.insecure=false  # allow without providing ssl certificate
      - --api.dashboard=${TRAEFIK_DASHBOARD_ENABLE:-true}  # enable dashboard
      - "--global.sendAnonymousUsage=false"
      - "--global.checkNewVersion=false"
      - --providers.docker=true # enable docker as provider
      - --providers.docker.exposedbydefault=false  # do not expose every container, only those with labels
      - "--providers.docker.network=traefik-public"
      - --providers.file.directory=/etc/traefik/dynamic
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.domains[0].main=${HOST_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${HOST_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[1].main=${HOST_DOMAIN_BALEAL}
      - --entrypoints.websecure.http.tls.domains[1].sans=*.${HOST_DOMAIN_BALEAL}

    labels: # labels for traefik itself, for dashboard
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.${HOST_DOMAIN}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_MIDDLEWARE_USERPASSWD}

  #crowdsec:
  #  container_name: crowdsec
  #  image: crowdsecurity/crowdsec:latest
  #  environment:
  #    GID: "${GID-1000}"
  #    COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/sshd"
  #  volumes:
  #    - "/etc/localtime:/etc/localtime:ro"
  #    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #    - "${CROWDSEC_FOLDER}:/etc/crowdsec"
  #    - "${CROWDSEC_FOLDER}/data:/var/lib/crowdsec/data"
  #    - "/var/log/auth.log:/var/log/auth.log:ro"
  #    - "/var/log/crowdsec:/var/log/crowdsec:ro"
  #  restart: unless-stopped
  #  security_opt:
  #    - no-new-privileges=true
  #  hostname: crowdsec


networks:
  traefik-public:
    name: traefik-public
