version: '3.8'

services:

  caddy:
    container_name: caddy
    image: caddy:2.4.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  hugo-server:
    build:
      context: ./hugo
    restart: always
    depends_on:
      - caddy

  vaultwarden:  # no dockerfile for this
    image: vaultwarden/server:latest
    volumes:
      - ~/vw-data/:/data/
    expose:
      - 80
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: