version: '3.8'

services:
  traefik:
    image: traefik:v2.10.7
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    command:
      - --log.level=DEBUG
      - --api.dashboard=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # HTTPS redirect
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/dynamic/traefik.yaml  # mount dynamic configuration file
      - ~/.certs:/etc/certs/:ro
    restart: always
    networks:
      - traefik

  hugo-server:
    container_name: hugo-server
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.hugo-server.entrypoints=websecure"
      - "traefik.http.routers.hugo-server.tls=true"
      - "traefik.http.routers.hugo-server.rule=Host(`jondef.me`)"
      - "traefik.http.services.hugo-server.loadbalancer.server.port=80"

    volumes:
      - hugo_public:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on:
      - hugo-compile
    networks:
      - traefik

  hugo-compile:
    container_name: hugo-compile
    build:
      context: ./hugo
    command: hugo
    volumes:
      - hugo_public:/src/public
    restart: "no"


  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.jondef.me`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
    volumes:
      - ~/vaultwarden-data/:/data/
    expose:
      - 80
    restart: unless-stopped
    networks:
      - traefik

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minecraft.rule=Host(`minecraft.jondef.me`)"
      - "traefik.http.routers.minecraft.entrypoints=web"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      JVM_OPTS: "-Xmx2000M -Xms2000M"
      STOP_SERVER_ANNOUNCE_DELAY: "5"
      MOTD: "A §l§cMinecraft§r §nserver"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      OPS: |
        16b17019-454d-4332-8c52-dfd3440874b7
      WHITELIST_ENABLED: "true"
      WHITE_LIST: |
        33d70dfd-cf46-42df-ba02-cf747c40a5fa, GeorgeSwiss
        16b17019-454d-4332-8c52-dfd3440874b7, BoLo_
    volumes:
      - ~/minecraft_data/:/data
    restart: unless-stopped

volumes:
  hugo_public:

networks:
  traefik:
