version: '3.8'

services:
  hugo-server:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: always

  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - ~/vw-data/:/data/
    expose:
      - 443
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: