version: '3.8'
# todo: https://github.com/Stirling-Tools/Stirling-PDF

services:
  traefik:
    image: traefik:v2.10.7
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"  # allow without providing ssl certificate
      - "--providers.docker=true" # enable docker as provider
      - "--api.dashboard=true"  # enable dashboard
      - "--providers.docker.exposedbydefault=false"  # do not expose every container, only those with labels
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565/udp"  # for minecraft
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/dynamic/traefik.yaml:ro  # mount dynamic configuration file
      - ~/.certs:/etc/certs/:ro
    restart: always
    networks:
      - traefik_net
    labels:  # labels for traefik itself, for dashboard
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"

        - "traefik.http.routers.traefik_https.rule=Host(`traefik.jondef.me`)"
        - "traefik.http.routers.traefik_https.entrypoints=websecure"
        - "traefik.http.routers.traefik_https.tls=true"

        - "traefik.http.routers.traefik_https.service=api@internal"
        - "traefik.http.routers.traefik_https.middlewares=traefik-auth"

        # generate with htpasswd -nb admin password (dollar signs need to be doubled)
        - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$1XqOGJR7$$uzAsayMj.Nk0.DHP5UYe51"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.jondef.me`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"  # specify port of whoami service
    networks:
      - traefik_net

  hugo-server:
    container_name: hugo-server
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.hugo-server.entrypoints=websecure"
      - "traefik.http.routers.hugo-server.tls=true"
      - "traefik.http.routers.hugo-server.rule=Host(`jondef.me`)"
      - "traefik.http.services.hugo-server.loadbalancer.server.port=80"
    volumes:
      - hugo_public:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on:
      - hugo-compile
    networks:
      - traefik_net

  hugo-compile:
    container_name: hugo-compile
    build:
      context: ./hugo
    command: hugo
    volumes:
      - hugo_public:/src/public:wr
    restart: "no"

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.jondef.me`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    volumes:
      - ~/vaultwarden-data/:/data/
    restart: unless-stopped
    networks:
      - traefik_net

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"

      - "traefik.udp.routers.minecraft.entrypoints=minecraft"
      - "traefik.udp.routers.minecraft.service=minecraft"
      - "traefik.udp.services.minecraft.loadbalancer.server.port=25565"
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      JVM_OPTS: "-Xmx2000M -Xms2000M"
      STOP_SERVER_ANNOUNCE_DELAY: "5"
      MOTD: "A §l§cMinecraft§r §nserver"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      OPS: |
        16b17019-454d-4332-8c52-dfd3440874b7
      WHITELIST_ENABLED: "true"
      WHITE_LIST: |
        33d70dfd-cf46-42df-ba02-cf747c40a5fa, GeorgeSwiss
        16b17019-454d-4332-8c52-dfd3440874b7, BoLo_
    volumes:
      - ~/minecraft_data/:/data
    restart: unless-stopped
    networks:
      - traefik_net

volumes:
  hugo_public: {}

networks:
  traefik_net: {}
