version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTPS redirect
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'

    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ~/.certs:/certs/:ro
    restart: always

  hugo-server:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hugo-server.rule=Host(`jondef.me`)"
      - "traefik.http.routers.hugo-server.entrypoints=web"
    volumes:
      - hugo_public:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on:
      - hugo-compile

  hugo-compile:
    container_name: hugo-server
    build:
      context: ./hugo
    command: hugo
    volumes:
      - hugo_public:/src/public
    restart: "no"


  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.jondef.me`)"
      - "traefik.http.routers.vaultwarden.entrypoints=web"
    volumes:
      - ~/vaultwarden-data/:/data/
    expose:
      - 80
    restart: unless-stopped

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minecraft.rule=Host(`minecraft.jondef.me`)"
      - "traefik.http.routers.minecraft.entrypoints=web"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      JVM_OPTS: "-Xmx2000M -Xms2000M"
      STOP_SERVER_ANNOUNCE_DELAY: "5"
      MOTD: "A §l§cMinecraft§r §nserver"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      OPS: |
        16b17019-454d-4332-8c52-dfd3440874b7
      WHITELIST_ENABLED: "true"
      WHITE_LIST: |
        33d70dfd-cf46-42df-ba02-cf747c40a5fa, GeorgeSwiss
        16b17019-454d-4332-8c52-dfd3440874b7, BoLo_
    volumes:
      - ~/minecraft_data/:/data
    restart: unless-stopped

volumes:
  hugo_public:
