version: '3.8'

services:
  hugo-server:
    build:
      context: ./
    ports:
      - "80:80"
    restart: always

  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - ~/vw-data/:/data/
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config: