services: 
  guacd:
    image: guacamole/guacd
    container_name: guacd
    hostname: guacd
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/guacd/drive:/drive:rw
      - ${DOCKERDIR}/guacd/record:/record:rw
    networks:
      - guacamole-network

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    hostname: guacamole
    restart: unless-stopped
    #volumes:
    #  - ./services/guacamole/home:/etc/guacamole:rw
    depends_on:
      - guacd
      - guacamole-db
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: guacamole-db
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      #MYSQL_HOSTNAME: guacamole-db
      #MYSQL_DATABASE: guacamole_db
      #MYSQL_USER: guacamole_user
      #MYSQL_PASSWORD: ${GUACAMOLE_PASSWORD}
      #TOTP_ENABLED: 'true'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.guacamole.rule=Host(`guacamole.${HOST_DOMAIN}`)'
      - "traefik.http.routers.guacamole.service=guacamole"
      #- 'traefik.http.routers.guacamole.entrypoints=web-secure'
      - "traefik.http.routers.guacamole.middlewares=authelia@docker,guacprefix"
      - 'traefik.http.routers.guacamole.tls=true'
      #- "traefik.http.routers.guacamole.tls.certresolver=myresolver"
      #- "traefik.http.routers.guacamole.middlewares=guac-auth,guacprefix"
      #- "traefik.http.middlewares.guac-auth.basicauth.users=USERNAME:PASSWORD"
      - "traefik.http.middlewares.guacprefix.addprefix.prefix=/guacamole"
      - "traefik.http.services.guacamole.loadBalancer.server.port=8080"
      #- "traefik.http.routers.guacamole.tls.domains[0].main=*.${DOMAIN}"
      #- "traefik.http.routers.guacamole.tls.options=myTLSOptions@file"
      #- "traefik.http.routers.guacamole.middlewares=guacamoleMdl"
    networks:
      - guacamole-network
      - traefik-public


  guacamole-db:
    image: postgres:13.4-buster
    container_name: guacamole-db
    hostname: guacamole-db
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      POSTGRES_DB: guacamole_db
      PGDATA: /var/lib/postgresql/data/guacamole
    restart: unless-stopped
    volumes:
      - ./services/guacamole/init/initdb.sql:/initdb.sql  #DB configuration file
      - ./services/guacamole/init/:/docker-entrypoint-initdb.d  # make sure dir is `chmod +x` 
      - ${DOCKERDIR}/guacamole/pgdata:/var/lib/postgresql/data:Z
      - ${DOCKERDIR}/guacamole/guac-data/database:/var/lib/mysql/:rw
    networks:
      - guacamole-network

networks:
  traefik-public: { }
  guacamole-network: { }
