
services:

  stirling:
    container_name: stirling
    image: frooodle/s-pdf:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling.entrypoints=websecure"
      - "traefik.http.routers.stirling.rule=Host(`pdf.${HOST_DOMAIN}`)"
      - "traefik.http.routers.stirling.service=stirling@docker"
      - "traefik.http.services.stirling.loadbalancer.server.port=8080"
    volumes:
      - ${DOCKERDIR}/stirling-data/trainingData:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - ${DOCKERDIR}/stirling-data/extraConfigs:/configs
      - ${DOCKERDIR}/stirling-data/customFiles:/customFiles/
      - ${DOCKERDIR}/stirling-data/logs:/logs/
    restart: unless-stopped
    networks:
      - traefik-public

networks:
  traefik-public: { }
