version: '3.8'

services:
  hugo-server:
    container_name: hugo-server
    build:
      context: ./services/hugo/
      dockerfile: ./services/hugo/Dockerfile_prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hugo-server.entrypoints=websecure"
      - "traefik.http.routers.hugo-server.rule=Host(`${HOST_DOMAIN}`)"
      - "traefik.http.services.hugo-server.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - traefik_net

networks:
  traefik_net: { }