# Dockerfile for Production

FROM alpine:3.19 as build
RUN apk add --no-cache hugo
COPY . /src
WORKDIR /src

# Production specific build step
RUN echo "Running in production mode" && hugo

# In production, no CMD is needed as the build step has already generated the static files
