# Build stage for Hugo
FROM alpine:3.19 as build
RUN apk add --no-cache hugo
COPY . /src
WORKDIR /src
RUN hugo

# Final stage with Nginx
FROM nginx:alpine
COPY --from=build /src/public /usr/share/nginx/html
EXPOSE 80
