# For development in Pycharm:
# Bind ports: 1313:1313

FROM alpine:3.19
RUN apk add --no-cache hugo
COPY . /src
WORKDIR /src

# Development specific command
CMD hugo server --bind 0.0.0.0 --disableFastRender

EXPOSE 1313
