version: '3.8'

services:


  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.${HOST_DOMAIN}`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    volumes:
      - ~/vaultwarden-data/:/data/
    restart: unless-stopped
    networks:
      - traefik_net

networks:
  traefik_net: { }

