version: '3'

networks:
  traefik_net: { }

# https://github.com/oznu/docker-cloudflare-ddns

services:
  cloudflare-ddns:
    container_name: cloudflare_ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CF_DNS_API_TOKEN}
      - ZONE=${HOST_DOMAIN}
      #- SUBDOMAIN=subdomain
      - PROXIED=true
    labels:
      - traefik.enable=false