
networks:
  traefik-public: { }

# https://github.com/oznu/docker-cloudflare-ddns

services:
  cloudflare-ddns-mercantus-ch:
    container_name: cloudflare_ddns_mercantus_ch
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CF_DNS_API_TOKEN}
      - ZONE=${HOST_DOMAIN_MERC_CH}
      #- SUBDOMAIN=subdomain
      # I don't use subdomains:
      # A @ <IP>
      # CNAME * @
      - PROXIED=true
    labels:
      - traefik.enable=false

  cloudflare-ddns-jondef-me:
    container_name: cloudflare_ddns_jondef_me
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CF_DNS_API_TOKEN}
      - ZONE=${HOST_DOMAIN}
      #- SUBDOMAIN=subdomain
      # I don't use subdomains:
      # A @ <IP>
      # CNAME * @
      - PROXIED=true
    labels:
      - traefik.enable=false
