
services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ittools.entrypoints=websecure"
      - "traefik.http.routers.ittools.rule=Host(`tools.${HOST_DOMAIN}`)"
      - "traefik.http.services.ittools.loadbalancer.server.port=80"
    networks:
      - traefik-public