services: 

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    hostname: guacamole
    restart: unless-stopped
    depends_on:
      - guacd
      - guacamole-db
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: guacamole-db
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: ${GUAC_USERNAME}
      POSTGRESQL_PASSWORD: ${GUAC_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.guacamole.entrypoints=websecure
      - traefik.http.routers.guacamole.tls.certresolver=cloudflare
      - traefik.http.routers.guacamole.rule=Host(`vdi.${HOST_DOMAIN}`)
      - traefik.http.routers.guacamole.middlewares=authelia@docker,guacprefix
      - traefik.http.routers.guacamole.tls=true
      - traefik.http.middlewares.guacprefix.addprefix.prefix=/guacamole
      - traefik.http.services.guacamole.loadBalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - traefik-public
      - guacamole-network

  guacd:
    image: guacamole/guacd
    container_name: guacd
    hostname: guacd
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/guacd/drive:/drive:rw
      - ${DOCKERDIR}/guacd/record:/record:rw
    networks:
      - guacamole-network

  guacamole-db:
    image: postgres:13.4-buster
    container_name: guacamole-db
    hostname: guacamole-db
    environment:
      POSTGRES_USER: ${GUAC_USERNAME}
      POSTGRES_PASSWORD: ${GUAC_PASSWORD}
      POSTGRES_DB: guacamole_db
      PGDATA: /var/lib/postgresql/data/guacamole
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/guacamole/pgdata:/var/lib/postgresql/data:Z
      - ${DOCKERDIR}/guacamole/guac-data/database:/var/lib/mysql/:rw
    networks:
      - guacamole-network

networks:
  traefik-public:
    external: true
  guacamole-network: { }
