version: "3"

services:
    tailscale:
        container_name: tailscale
        image: tailscale/tailscale
        restart: always
        volumes:
            - ~/tailscale_data/:/var/lib/tailscale
            - /dev/net/tun:/dev/net/tun
        privileged: true  #Grants extended privileges, necessary for network management
        network_mode: host # Uses the host's network, allowing Tailscale to manage network interfaces directly
        cap_add:  # Adds necessary network capabilities
            - NET_ADMIN
        environment:
            - PUID=998
            - PGID=100
            - TS_USERSPACE=true
            - TS_ROUTES=172.17.0.0/16  # Specifies the network routes that should be advertised to the Tailscale network
            - TS_AUTHKEY=${TAILSCALE_KEY}
            - TS_EXTRA_ARGS=--advertise-exit-node
