version: '3'
#https://immich.app/docs/install/environment-variables

networks:
  traefik_net: { }
  immich-db: { }

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ./immich/:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/data/nextcloud/:/mnt/nextcloud:ro
    networks:
      - traefik_net
    user: 33:33
    environment:
      - PGID=33
      - PUID=33
      - DB_PASSWORD=123456
      - DB_HOSTNAME=immich_database
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - UPLOAD_LOCATION=/usr/src/app/upload
      - TYPESENSE_API_KEY=changeme
    depends_on:
      - immich_redis
      - immich_database
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.rule=Host(`photos.${HOST_DOMAIN}`)
      - traefik.http.services.immich.loadbalancer.server.scheme=http
      - traefik.http.services.immich.loadbalancer.server.port=3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    restart: unless-stopped
    networks:
      - traefik_net
    user: 33:33
    environment:
      - PGID=33
      - PUID=33
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich_database
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - REDIS_HOSTNAME=immich_redis
      - TZ=${TZ}
      - TYPESENSE_API_KEY=changeme
      - UPLOAD_LOCATION=/usr/src/app/upload
    volumes:
      - ./immich/:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/main/data/nextcloud/:/mnt/nextcloud:ro
    depends_on:
      - immich_redis
      - immich_database

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - traefik_net
    volumes:
      - /etc/immich/model-cache/:/cache
    restart: unless-stopped

  immich_redis:
    container_name: immich_redis
    networks:
      - traefik_net
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: unless-stopped

  immich_database:
    container_name: immich_database
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    networks:
      - traefik_net
    environment:
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
    volumes:
      - ./immichdb/:/var/lib/postgresql/data
    restart: unless-stopped
