
services:

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    user: "1000:1000"
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      JVM_OPTS: "-Xmx4000M -Xms4000M"
      STOP_SERVER_ANNOUNCE_DELAY: "5"
      MOTD: "A §l§cMinecraft§r §nserver"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      OPS: |
        GeorgeSwiss
        BoLo_
      WHITELIST_ENABLED: "true"
      WHITE_LIST: |
        GeorgeSwiss
        BoLo_
      ENABLE_RCON: false
    volumes:
      - ${DOCKERDIR}/minecraft_data/:/data
    restart: unless-stopped
    networks:
      - traefik-public


networks:
  traefik-public: { }
