version: '3.8'

services:

  # region monica
  monica:
    image: monica
    depends_on:
      - mysql
      - traefik
    environment:
      - DB_HOST=mysql
      - APP_ENV=production
      - APP_URL=https://monica.jondef.me/
      - DB_DATABASE=monica
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
      - LOG_CHANNEL=stderr
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - QUEUE_DRIVER=sync
    restart: unless-stopped
    volumes:
      - monica_data:/var/www/html/storage
    networks:
      - monica_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.monica.entrypoints=websecure"
      - "traefik.http.routers.monica.tls=true"
      - "traefik.http.routers.monica.rule=Host(`monica.jondef.me`)"
      - "traefik.http.routers.monica.service=monica@docker"
      - "traefik.http.services.monica.loadbalancer.server.port=80"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - monica_net
  # endregion


volumes:
  mysql_data: { }


networks:
  traefik_net: { }
  monica_net:
    driver: bridge
