
version: '3'

networks:
  traefik_net: { }

volumes:
  nextcloud:
  nextcloud_db:

# https://github.com/linuxserver/docker-nextcloud

services:

  nextcloud:
    image: nextcloud:${NEXTCLOUD_DOCKER_TAG:-latest}
    container_name: ${NEXTCLOUD_CONTAINER_NAME:-nextcloud}
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
       - nextcloud:/var/www/html
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - MYSQL_PASSWORD=1234567890
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_CONTAINER_NAME:-nextcloud}.${HOST_DOMAIN}`)
      - traefik.http.routers.nextcloud.service=nextcloud
      - traefik.http.services.nextcloud.loadbalancer.server.scheme=http
      - traefik.http.services.nextcloud.loadbalancer.server.port=80

  nextcloud_db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890
      - MYSQL_PASSWORD=1234567890
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud