version: '3.8'

services:

  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server
    labels:
      - "traefik.enable=true"

      - "traefik.udp.routers.minecraft.entrypoints=minecraft"
      - "traefik.udp.routers.minecraft.service=minecraft"
      - "traefik.udp.services.minecraft.loadbalancer.server.port=25565"
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      JVM_OPTS: "-Xmx2000M -Xms2000M"
      STOP_SERVER_ANNOUNCE_DELAY: "5"
      MOTD: "A §l§cMinecraft§r §nserver"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "5"
      OPS: |
        16b17019-454d-4332-8c52-dfd3440874b7
      WHITELIST_ENABLED: "true"
      WHITE_LIST: |
        33d70dfd-cf46-42df-ba02-cf747c40a5fa, GeorgeSwiss
        16b17019-454d-4332-8c52-dfd3440874b7, BoLo_
    volumes:
      - ~/minecraft_data/:/data
    restart: unless-stopped
    networks:
      - traefik_net


networks:
  traefik_net: { }
