version: '3.8'  # You can use a different version if required

# https://www.youtube.com/watch?v=GyllRd2E6fg&t=198s

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling.entrypoints=websecure"
      - "traefik.http.routers.stirling.rule=Host(`ollama.${HOST_DOMAIN}`)"
      - "traefik.http.services.stirling.loadbalancer.server.port=11434"

volumes:
  ollama:
