
# https://www.youtube.com/watch?v=GyllRd2E6fg&t=198s

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.rule=Host(`ollama.${HOST_DOMAIN}`)"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"

volumes:
  ollama:
