kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.3
          args:
            - --log.level=DEBUG
            - --log.format=common
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --api.dashboard=true
            - --api.insecure
            - --providers.kubernetesingress
            # Global redirect from HTTP to HTTPS

            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entryPoint.permanent=true
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls=true
            - --entrypoints.websecure.http.tls.domains[0].main=${HOST_DOMAIN}
            - --entrypoints.websecure.http.tls.domains[0].sans=*.${HOST_DOMAIN}

            # Let's Encrypt configuration - using DNS challenge with Cloudflare
            - --certificatesresolvers.cloudflare.acme.dnschallenge=true
            - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=0
            - --certificatesresolvers.cloudflare.acme.email=jdefilla@gmail.com
            - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json
            # STAGING Let's Encrypt - comment out this line for production
            - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
          env:
            - name: CLOUDFLARE_DNS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-dns-api-token-secret
                  key: CLOUDFLARE_DNS_API_TOKEN
          volumeMounts:
            - name: nfs-storage
              mountPath: /data/
              subPath: traefikkk
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-general-pvc
