apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: dashboard
      nodePort: 30000
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: NodePort
  ports:
    - name: http
      targetPort: web
      port: 80
      nodePort: 30080
    - name: https
      targetPort: websecure
      port: 443
      nodePort: 30443
  selector:
    app: traefik
