
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    environment:
      - APP_NAME="Gitea"
      - USER_UID=1000
      - USER_GID=1000
      - USER=git
      - RUN_MODE=prod
      - DOMAIN=git.${HOST_DOMAIN}
      - SSH_DOMAIN=git.${HOST_DOMAIN}
      - HTTP_PORT=3000
      - ROOT_URL=https://git.${HOST_DOMAIN}
      - SSH_PORT=222
      - SSH_LISTEN_PORT=22
      - DB_TYPE=sqlite3
      - GITEA__cache__ENABLED=true
      - GITEA__cache__ADAPTER=redis
      - GITEA__cache__HOST=redis://gitea-cache:6379/0?pool_size=100&idle_timeout=180s
      - GITEA__cache__ITEM_TTL=24h
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_USERNAME}
      - GITEA__database__PASSWD=${GITEA_PASSWORD}
    networks:
      - traefik-public
      - git_net
    volumes:
      - ${DOCKERDIR}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls.certresolver=cloudflare
      - traefik.http.routers.gitea.rule=Host(`git.${HOST_DOMAIN}`)
      - traefik.http.services.gitea-service.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true

  gitea-cache:
    container_name: gitea-cache
    image: redis:6-alpine
    restart: unless-stopped
    networks:
      - git_net

  gitea-db:
    container_name: gitea-db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${GITEA_USERNAME}
      - POSTGRES_PASSWORD=${GITEA_PASSWORD}
      - POSTGRES_DB=gitea
    networks:
      - git_net
    volumes:
      - ${DOCKERDIR}/giteadb:/var/lib/postgresql/data

networks:
  traefik-public:
    external: true
  git_net: { }