
### CONFIG_PATH_PAIRDROP IS DEFINED IN MANAGE SCRIPT

services:
  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    restart: unless-stopped
    volumes:
      - ${DOCKERDIR}/pairdrop/rtc_config.json:/home/node/app/rtc_config.json
    environment:
      #- IPV6_LOCALIZE=4
      - PUID=1000 # UID to run the application as
      - PGID=1000 # GID to run the application as
      - WS_FALLBACK=true # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
      - RATE_LIMIT=true # Set to true to limit clients to 1000 requests per 5 min.
      - RTC_CONFIG=/home/node/app/rtc_config.json # Set to the path of a file that specifies the STUN/TURN servers.
      - DEBUG_MODE=false # Set to true to debug container and peer connections.
      - TZ=${TZ} # Time Zone
    labels:
      - traefik.enable=true
      - traefik.http.routers.pairdrop.entrypoints=websecure
      - traefik.http.routers.pairdrop.tls.certresolver=cloudflare
      - traefik.http.routers.pairdrop.rule=Host(`airdrop.${HOST_DOMAIN}`)
      - traefik.http.services.pairdrop.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - traefik-public

  coturn_server:
    image: coturn/coturn:latest
    container_name: coturn
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    volumes:
      - ${DOCKERDIR}/pairdrop/turnserver.conf:/etc/coturn/turnserver.conf
      - ${DOCKERDIR}/pairdrop/ssl/:/etc/coturn/ssl/
    ports:
      - 1000:3478   # 80 + 920
      - 1000:3478/udp
      - 1363:5349   # 443 + 920
      - 1363:5349/udp
      - 10000-10050:10000-10050/udp
    # see guide at docs/host-your-own.md#coturn-and-pairdrop-via-docker-compose
    networks:
      - coturn


networks:
  coturn: { }
  traefik-public:
    external: true